spring.application.name=SmartPrecence
spring.datasource.url=jdbc:postgresql://localhost:5432/smartpresence_db
spring.datasource.username=postgres
spring.datasource.password=338833
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081